import {
  Alignment,
  Autoformat,
  AutoImage,
  AutoLink,
  BlockQuote,
  Bold,
  ClassicEditor,
  Essentials,
  FontColor,
  FontSize,
  Heading,
  Highlight,
  HorizontalLine,
  Image,
  ImageCaption,
  ImageInsert,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  Italic,
  Link,
  LinkImage,
  List,
  MediaEmbed,
  MediaEmbedToolbar,
  // Paragraph,
  SourceEditing,
  Strikethrough,
  // Table,
  // TableToolbar,
  Underline,
} from 'ckeditor5';

class Editor extends ClassicEditor {}

Editor.builtinPlugins = [
  Alignment,
  Autoformat,
  Bold,
  Italic,
  Strikethrough,
  Underline,
  BlockQuote,
  Essentials,
  FontColor,
  FontSize,
  Heading,
  Highlight,
  HorizontalLine,
  AutoImage,
  Image,
  ImageCaption,
  ImageInsert,
  ImageResize,
  ImageStyle,
  ImageToolbar,
  ImageUpload,
  Indent,
  IndentBlock,
  AutoLink,
  Link,
  LinkImage,
  List,
  MediaEmbed,
  MediaEmbedToolbar,
  // Paragraph,
  SourceEditing,
  // Table,
  // TableToolbar,
];

Editor.defaultConfig = {
  toolbar: {
    items: [
      'undo',
      'redo',
      '|',
      'heading',
      '|',
      'fontSize',
      'fontColor',
      'highlight',
      '|',
      'bold',
      'italic',
      'underline',
      'strikethrough',
      '|',
      'alignment',
      'indent',
      'outdent',
      '|',
      'bulletedList',
      'numberedList',
      '|',
      'link',
      'blockQuote',
      'mediaEmbed',
      'horizontalLine',
      '|',
      'imageUpload',
      '|',
      'sourceEditing',
    ],
  },
  image: {
    toolbar: [
      'imageStyle:alignLeft',
      'imageStyle:alignCenter',
      'imageStyle:alignRight',
      '|',
      'imageTextAlternative',
      'toggleImageCaption',
      'linkImage',
    ],
  },
  table: {
    contentToolbar: ['tableColumn', 'tableRow', 'mergeTableCells'],
  },
  mediaEmbed: {
    toolbar: ['mediaEmbed'],
  },
};

export default Editor;
